apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: prod-issuer
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
    kubernetes.io/ingress.class: nginx
  name: bepm.io
  namespace: default
spec:
  rules:
    - host: bepm.io
      http:
        paths:
          - path: /
            backend:
              serviceName: cloudflare-k8s-tls
              servicePort: 80
  tls:
    - hosts:
        - bepm.io
      secretName: bepm-io-tls
